chown -R root:www-data core/cache
chown -R root:www-data core/config
chown -R root:www-data core/components
chown -R root:www-data core/export
chown -R root:www-data core/packages
chown -R root:www-data assets
chmod -R 775 core/cache
chmod -R 775 core/config
chmod -R 775 core/components
chmod -R 775 core/export
chmod -R 775 core/packages
chmod -R 775 assets
